### ISSUE TITLE
Gamma and beat Radiation dosn't travel through air.

### ISSUE THREAD

**Issue by Mattifine** [SpicyBagpipes/KJW_Radiate#2]
Gamma and Beta Radiation dosn't travel through air.
In the example I have added a 10 count gamma source to the campfire and it appares when I am right on top of the camp fire but only 10 m way it is gone, see pictures.
![20240222142728_1](https://github.com/SpicyBagpipes/KJW_Radiate/assets/77750642/27d36c01-ff96-4da1-a106-55aab12f052d)
![20240222142746_1](https://github.com/SpicyBagpipes/KJW_Radiate/assets/77750642/c7f19af6-cbbd-43c0-bfc5-9be614abd758)
![20240222142758_1](https://github.com/SpicyBagpipes/KJW_Radiate/assets/77750642/380caad0-221b-41c0-a4d3-c80104390683)

**Comment by Mattifine** [comment]
A 1000 count Gamma source only show 10 counts at 15m away

**Comment by SpicyBagpipes** [comment]
Whilst realistic this is admittedly not the best for gameplay -- I'll add a gamified version of distance calculation
